#!/usr/bin/env bash
#
# srm - Secure Remove
# Safely removes files by overwriting them with random data before deletion
#
# Copyright (C) 2025 João Maurício (Jean0t/noether)
# Licensed under GPL-3.0-or-later
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -u


#================================================================
# VARIABLES
readonly AUTHOR='Joao Mauricio (jean0t/noether)'
readonly VERSION='2.0.2'


# operational constants
SHRED_OVERWRITES=10
declare -a SHRED_OPTS
declare -a RM_OPTS
SHRED_OPTS+=(-z)

# flags are initialized false
RECURSIVE=0
VERBOSE=0
FORCE=0
DRY_RUN=0

#================================================================
# VERIFICATIONS
verify_dependencies() {
    if ! command -v shred 2>/dev/null >&2; then
	echo 'shred does not exists' && exit 1
    fi

    if ! command -v rm 2>/dev/null >&2; then
	echo 'rm does not exists' && exit 1
    fi
}


#================================================================
# INFO
show_version() {
    echo -e \
	 "srm (Secure Remove) ${VERSION}
Copyright (C) 2025 ${AUTHOR}
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by ${AUTHOR}"
}

show_help() {
    echo -e \
	 "Usage: srm [OPTIONS] FILE...

Securely remove files by overwriting them with random data before deletion.

OPTIONS:
    -h          Display this help message and exit
    -v          Display version information and exit
    -V		Display verbose output
    -f          Ignore nonexistent files, never prompt
    -n		Dry Run, doesn't operates but shows which files it would operate on"
}


#================================================================
# OPERATIONS

secure_remove_file() {
    local file="$1"

    #====== Start file verifications
    if [[ ! -e "$file" && ${FORCE} -eq 0 ]]; then
	echo "File doesn't exists"
	return 1
    fi
    
    if [[ -d "$file" ]]; then
	echo "Appointed data isn't a file but a directory"
	echo "Tip: use the command 'find' with srm or shell glob like /test/**/* to select files to deletion in a directory"
	return 1
    fi

    if [[ -L "${file}" ]]; then
	echo "Won't operate in a symbolic link: ${file}"
	return 1
    fi
    #====== End file verifications

    if [[ ${DRY_RUN:-0} -eq 1 ]]; then
	echo "Would operate in the file: ${file}"
	return 0
    fi
    
    if shred ${SHRED_OPTS[*]} -n ${SHRED_OVERWRITES} "$file" 2>/dev/null; then
	[[ ${VERBOSE} -eq 1 ]] && echo "${file} was overwritten ${SHRED_OVERWRITES} times"

    elif [[ ${FORCE} -eq 0 ]]; then
        echo "Failed to overwrite"
	return 1
    fi

    if rm ${RM_OPTS[*]} "$file" 2>/dev/null; then
	[[ ${VERBOSE} -eq 1 ]] && echo "${file} was removed successfully"

    else
	echo "Failed to remove file"
	return 1
    fi

    return 0
}

#================================================================
# Main

main() {
    verify_dependencies

    while getopts ":vVhfrn" opts; do
	case "$opts" in
	    h)
		show_help
		exit 0
		;;

	    v)
		show_version
		exit 0
		;;

	    V)
		VERBOSE=1
		RM_OPTS+=(-v)
		;;
	    
	    f)
		FORCE=1
		RM_OPTS+=(-f)
		SHRED_OPTS+=(-f)
		;;

	    n)
		DRY_RUN=1
		;;

	    *)
		show_help
		exit 1
		;;
	esac
    done
    shift $((OPTIND - 1))


    if [[ $# -eq 0 ]]; then
	echo 'No file was specified'
	echo "Try: 'srm -h' for more information"
	exit 1
    fi


    for file in "$@"; do
	if ! secure_remove_file "${file}"; then
	    echo "Operation aborted: failed to operate with ${file}"
	    exit 1
	fi
    done
}

# Entrypoint
main "$@"
