#!/usr/bin/env bash
#
# srm - Secure Remove
# Safely removes files by overwriting them with random data before deletion
#
# Copyright (C) 2025 João Maurício (Jean0t/noether)
# Licensed under GPL-3.0-or-later
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -eu


#================================================================
# VARIABLES
readonly AUTHOR='Joao Mauricio (jean0t/noether)'
readonly VERSION='1.0.2'

# flags are initialized false
RECURSIVE=0
FORCE=0
#================================================================
# INFO
show_version() {
    echo -e \
	 "srm (Secure Remove) ${VERSION}
Copyright (C) 2025 ${AUTHOR}
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by ${AUTHOR}"
}

show_help() {
    echo -e \
	 "Usage: srm [OPTIONS] FILE...

Securely remove files by overwriting them with random data before deletion.

OPTIONS:
    -h          Display this help message and exit
    -v          Display version information and exit
    -f          Ignore nonexistent files, never prompt
    -r          Remove directories and their contents recursively

OBS:
\t-f and -r aren't supported yet"
}


#================================================================
# Main
while getopts ":vhfr" opts; do
    case "$opts" in
	h)
	    show_help
	    exit 0
	    ;;

	v)
	    show_version
	    exit 0
	    ;;

	# currently those two do nothing
	# but they will be important in future updates
	f)
	    FORCE=1
	    ;;

	r)
	    RECURSIVE=1
	    ;;

	*)
	    show_help
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))


if [[ $# -gt 1 ]]; then
    shred -n 10 "${!#}" && rm "${@:1:$#-1}" "${!#}"
else
    shred -n 10 "${1}" && rm "${1}"
fi
